import React from 'react';
import { Schedule } from '../types';

interface PreviewScheduleProps {
  schedule: Omit<Schedule, 'id' | 'createdAt'>;
  onSave: () => void;
  onCancel: () => void;
}

export const PreviewSchedule: React.FC<PreviewScheduleProps> = ({ schedule, onSave, onCancel }) => {
  return (
    <div className="flex flex-col h-full bg-background">
      <div className="bg-white p-4 shadow-sm border-b">
        <h2 className="text-center font-bold text-lg text-gray-700">Preview Routine</h2>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        <div className="text-center mb-6">
            <div className="inline-block px-4 py-1 bg-primary/10 text-primary rounded-full text-sm font-bold mb-2">
                {schedule.type}
            </div>
            <h1 className="text-2xl font-bold text-gray-800">{schedule.title}</h1>
            <p className="text-gray-500 text-sm">Review steps generated by Gemini</p>
        </div>

        <div className="space-y-4">
            {schedule.steps.map((step, index) => (
                <div key={index} className="bg-white p-4 rounded-2xl shadow-sm flex items-start gap-4">
                    <div className="text-3xl bg-gray-50 w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0">
                        {step.emoji}
                    </div>
                    <div>
                        <h4 className="font-bold text-gray-800">{step.instruction}</h4>
                        <p className="text-sm text-primary italic">"{step.encouragement}"</p>
                    </div>
                </div>
            ))}
        </div>
      </div>

      <div className="p-4 bg-white border-t flex gap-4">
        <button 
            onClick={onCancel}
            className="flex-1 py-3 bg-gray-200 text-gray-700 rounded-xl font-bold"
        >
            Discard
        </button>
        <button 
            onClick={onSave}
            className="flex-1 py-3 bg-primary text-white rounded-xl font-bold shadow-lg"
        >
            Save & Start
        </button>
      </div>
    </div>
  );
};
